#! /usr/bin/env bash

word1="io"
word2="tl"
word3="yukinosu"

# Export variables for use in find -exec
export word1 word2 word3 word4

# Rename directories
find . -depth -type d -name 'com' -execdir mv {} "$word1" \;
find . -depth -type d -name 'resukisu' -execdir mv {} "$word2" \;
find . -depth -type d -name 'resukisu' -execdir mv {} "$word3" \;

# Replace inside files
find . -type f -exec sed -i \
    -e "s/com\.resukisu\.resukisu/$word1.$word2.$word3/g" \
    -e "s/io\.resukisu\.resukisu/$word4.$word2.$word3/g" \
    -e "s/com\.resukisu\.zako/$word1.$word2.zako/g" \
    -e "s/com\/resukisu\/resukisu/$word1\/$word2\/$word3/g" \
    -e "s/io\/resukisu\/resukisu/$word4\/$word2\/$word3/g" \
    -e "s/io_resukisu_resukisu/${word4}_${word2}_${word3}/g" \
    -e "s/com_resukisu_resukisu/${word1}_${word2}_${word3}/g" {} +
    
# Replace app label in AndroidManifest.xml
find . -name "AndroidManifest.xml" -exec sed -i 's/android:label="@string\/app_name"/android:label="YukinoSU"/g' {} \;